x-common-variables: &common-variables
  PLATFORM_ENV: demo-env

  OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces # for backend services
  OTLP_LOGS_ENDPOINT: http://otel-collector:4318/v1/logs # for backend services
  MULTIPLAYER_OTLP_COLLECTOR_ENDPOINT: https://api.multiplayer.app:443 # for web-app and otel-collector
  MULTIPLAYER_OTLP_DOC_SPAN_RATIO: 0.04
  MULTIPLAYER_OTLP_SPAN_RATIO: 0.05

  #  REACT_APP_PLATFORM_ENV: demo-env
  REACT_APP_BASE_API_URL: http://localhost:8080 # for frontend service
  #  REACT_APP_MULTIPLAYER_OTLP_DOC_SPAN_RATIO: 0.04
  #  REACT_APP_MULTIPLAYER_OTLP_SPAN_RATIO: 0.05

services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: mp-time-travel-envoy
    ports:
      - "8080:8080"
    depends_on:
      vault-of-time:
        condition: service_started
      dialogue-hub:
        condition: service_started
      timegate:
        condition: service_started
      epoch-engine:
        condition: service_started
      minds-of-time:
        condition: service_started
      web-app:
        condition: service_healthy
    volumes:
      - ./services/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./services/envoy/extensions/payload-otlp/target/wasm32-wasip1/release/otlp_capture_payload.wasm:/etc/istio/extensions/otlp_capture_payload.wasm

  epoch-engine: # dotnet
    build:
      context: ./services/epoch-engine
    container_name: mp-time-travel-epoch-engine
    hostname: mp-time-travel-epoch-engine
    restart: on-failure
    environment:
      <<: *common-variables
      ASPNETCORE_URLS: http://0.0.0.0:3000
      PORT: 3000
      SERVICE_VERSION: 0.0.1
    env_file:
      - ./.env
    # volumes:
    #   - ./services/epoch-engine:/source:cached

  vault-of-time: # go
    build:
      context: ./services/vault-of-time
    container_name: mp-time-travel-vault-of-time
    hostname: mp-time-travel-vault-of-time
    restart: on-failure
    environment:
      <<: *common-variables
      PORT: 3000
      SERVICE_VERSION: 0.0.1
    env_file:
      - ./.env
    # volumes:
    #   - ./services/vault-of-time:/app:cached

  dialogue-hub: # java
    build:
      context: ./services/dialogue-hub
    container_name: mp-time-travel-dialogue-hub
    hostname: mp-time-travel-dialogue-hub
    restart: on-failure
    environment:
      <<: *common-variables
      SERVER_PORT: 3000
      REDIS_HOST: mp-time-travel-redis
      REDIS_PORT: 6379
      REDIS_URI: redis://mp-time-travel-redis:6379
      SERVICE_VERSION: 0.0.1
    depends_on:
      redis:
        condition: service_started
    env_file:
      - ./.env
    # volumes:
    #   - ./services/dialogue-hub:/usr/app:cached

  timegate: # nodejs
    build:
      context: ./services/timegate
    container_name: mp-time-travel-timegate
    hostname: mp-time-travel-timegate
    restart: on-failure
    environment:
      <<: *common-variables
      PORT: 3000
      SERVICE_VERSION: 0.0.1
      DIALOGUE_HUB_SERVICE_URL: http://mp-time-travel-dialogue-hub:3000
      EPOCH_ENGINE_SERVICE_URL: http://mp-time-travel-epoch-engine:3000
      MINDS_OF_TIME_SERVICE_URL: http://mp-time-travel-minds-of-time:3000
      VAULT_OF_TIME_SERVICE_URL: http://mp-time-travel-vault-of-time:3000
      MONGODB_URI: mongodb://mongo:27017/time-travel-demo
    env_file:
      - ./.env
    # volumes:
    #   - ./services/timegate:/usr/src/app:cached

  minds-of-time: # python
    build:
      context: ./services/minds-of-time
    container_name: mp-time-travel-minds-of-time
    hostname: mp-time-travel-minds-of-time
    restart: on-failure
    environment:
      <<: *common-variables
      PORT: 3000
      SERVICE_VERSION: 0.0.1
    env_file:
      - ./.env
    # volumes:
    #   - ./services/minds-of-time:/usr/src/app:cached

  web-app:
    build:
      context: ./clients/web-app
      args:
        <<: *common-variables
        MULTIPLAYER_OTLP_KEY: ${MULTIPLAYER_OTLP_KEY}
        VERSION: 0.0.1
    container_name: mp-time-travel-web-app
    hostname: mp-time-travel-web-app
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 20s
      timeout: 30s
      retries: 3
      start_period: 15s
    env_file:
      - ./.env
    # volumes:
    #   - ./clients/mp-time-travel:/app:cached

  redis:
    image: redis:7.0.12-alpine
    container_name: mp-time-travel-redis
    hostname: mp-time-travel-redis
    command: redis-server
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    # ports:
    #   - "6379:6379"

  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:e9276a78341765d080347ee23f274f01e562fe5a
    container_name: otel-collector
    hostname: otel-collector
    restart: on-failure
    command: ["--config=/etc/otel/config.yaml"]
    env_file:
      - ./.env
    environment:
      <<: *common-variables
    volumes:
      - ./services/otel-collector/config.yaml:/etc/otel/config.yaml
  
  mongo:
    image: mongo:8.0.0
    container_name: mongo
    hostname: mongo
    restart: on-failure
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=time-travel-demo
    volumes:
      - time-travel-mongo-data:/data/db

volumes:
  time-travel-mongo-data:
