extensions:
  healthcheckv2:
    use_v2: true
    component_health:
      include_permanent_errors: false
      include_recoverable_errors: true
      recovery_duration: 5m
    http:
      endpoint: "0.0.0.0:13133"
      status:
        enabled: true
        path: "/health/status"
      config:
        enabled: true
        path: "/health/config"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"

processors:
  transform/set_trace_type:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(resource.attributes["multiplayer.trace_type"], Substring(trace_id.string, 0, 6))
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["multiplayer.trace_type"], Substring(trace_id.string, 0, 6))

  groupbytrace:
    wait_duration: 10s
    num_traces: 1000
    num_workers: 2

  batch:
    send_batch_size: 5
    send_batch_max_size: 5
    timeout: 3s

  memory_limiter/deb:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  memory_limiter/d0c:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

  resourcedetection/system:
    detectors: [ "system" ]
    system:
      hostname_sources: [ "os" ]

  filter/deb:
    error_mode: ignore
    traces:
      span:
        - 'resource.attributes["multiplayer.trace_type"] != "debdeb"'
        - 'attributes["http.target"] == "/jaeger/v1/traces"'
        - 'attributes["http.target"] == "/v1/traces"'
        - 'attributes["http.target"] == "/v1/logs"'
        - 'attributes["http.route"] == "/health"'
        - 'attributes["http.route"] == "/healthz"'
    logs:
      log_record:
        - 'resource.attributes["multiplayer.trace_type"] != "debdeb"'

  filter/d0c:
    error_mode: ignore
    traces:
      span:
        - 'attributes["multiplayer.trace_type"] != "d0cd0c"'
        - 'attributes["http.target"] == "/jaeger/v1/traces"'
        - 'attributes["http.target"] == "/v1/traces"'
        - 'attributes["http.target"] == "/v1/logs"'
        - 'attributes["http.route"] == "/health"'
        - 'attributes["http.route"] == "/healthz"'

  filter/not-d0c-deb:
    error_mode: ignore
    traces:
      span:
        - 'attributes["multiplayer.trace_type"] == "debdeb" and attributes["multiplayer.trace_type"] == "d0cd0c"'
        - 'attributes["http.target"] == "/jaeger/v1/traces"'
        - 'attributes["http.target"] == "/v1/traces"'
        - 'attributes["http.target"] == "/v1/logs"'
        - 'attributes["http.route"] == "/health"'
        - 'attributes["http.route"] == "/healthz"'

  probabilistic_sampler:
    sampling_percentage: 30

exporters:
  otlphttp/multiplayer:
    endpoint: https://api.multiplayer.app:443
    headers:
      Authorization: "${MULTIPLAYER_OTLP_KEY}"
    timeout: 10s
    encoding: json

service:
  telemetry:
    logs:
        level: "debug"  # Options: debug, info, warn, error
    # traces:
    #   processors:
    #     - batch:
    #         exporter:
    #           otlp:
    #             protocol: http/protobuf
    #             endpoint: http://localhost:6318

    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888

  extensions: [ healthcheckv2 ]
  pipelines:
    logs/deb:
      receivers: [ otlp ]
      processors:
        - filter/deb
        - transform/set_trace_type
        # - memory_limiter/deb
        - batch
      exporters: [ otlphttp/multiplayer ]
    traces/deb:
      receivers: [ otlp ]
      processors:
        - filter/deb
        - transform/set_trace_type
        # - memory_limiter/deb
        - resourcedetection/system
        - batch
      exporters: [ otlphttp/multiplayer ]
    traces/d0c:
      receivers: [ otlp ]
      processors:
        - filter/d0c
        - transform/set_trace_type
        - resourcedetection/system
        - batch
      exporters: [ otlphttp/multiplayer ]
    traces/random-d0c:
      receivers: [ otlp ]
      processors:
        - filter/not-d0c-deb
        - probabilistic_sampler
        - resourcedetection/system
        - batch
      exporters: [ otlphttp/multiplayer ]
