FROM python:3.9.5-slim-buster

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 3000

ENV FLASK_APP=src/app.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=3000", "--debug"]
